### ISSUE TITLE
How to generate the csv data inside **Paths** folder for a new given scene?

### ISSUE THREAD

**Issue by yyf17** [anton-jeran/MESH2IR#2]
Very nice work and thank you very much for sharing.
Read.me has a sentence
``
For 3 different indoor scenes, we have stored sample source-recevier locations in a csv format inside **Paths** folder.
"
The question I want to ask is how is this data obtained?
How to generate the csv data inside **Paths** folder for a new given scene?
Are there any tools or scripts to share?
Thank you.

**Comment by anton-jeran** [comment]
Hi,

Thank you for your interest in our project. We don't have a code to generate csv file for new environment. 

Neural Sound rendering part of our project is done by our co-author Zhenyu Tang (https://royjames.github.io/zhy/). He rendered the video and gave me coordinates in a CSV file. I wrote embed_generator.py to create embeddings using the coordinates.  The embedding can be created by appending a list like this.
embeddings = [mesh_path,folder_name,wave_name,source_list[s],listener_list[l]]
here 
mesh_path --> graph location
folder_name,wave_name --> folder location and wav file name to save the output.
source_list[s] --> Source location
listener_list[l] --> Listener location

If you need to get more information on the coordinate system (where origin is located) and writing csv file, you need to contact Zhenyu (https://royjames.github.io/zhy/). You also can find details about the dataset here (https://arxiv.org/pdf/2204.01787.pdf).

 Sorry, I could not help with regards to this problem.

**Comment by yyf17** [comment]
@anton-jeran Thank you.
