### ISSUE TITLE
The size of the RIR generated

### ISSUE THREAD

**Issue by yyf17** [anton-jeran/MESH2IR#3]
Very nice work and thank you very much for sharing.
The size of the RIR generated by "python3 evaluate.py" is very different from the size of the corresponding RIR of the training dataset (or GWA dataset). What's going on? Would you like to help?
Thank you!
## Size of RIR generated is 15.6KB  
path: "1aa91215-cba7-4c40-8b37-6b21584b5924/hybrid/L3_R0012.wav"
![image](https://user-images.githubusercontent.com/34536352/184101561-7afc756e-fa0e-49e5-97e7-1fc5b3be740b.png)
## Size of RIR in GWA or training dataset is 281.4KB 
path:"GWA_Dataset_small/1aa91215-cba7-4c40-8b37-6b21584b5924/L3_R0012.wav"
![image](https://user-images.githubusercontent.com/34536352/184101957-bacd576b-d90b-4601-b3f9-6a3544e5acbd.png)

**Comment by anton-jeran** [comment]
Hi 
The duration of the training dataset is more than the duration of the RIR predicted by our network. Our network predicts 0.25 seconds of the RIR. You can increase the model parameters and train the network to predicts large duration.

What we observe is that 0.25 seconds of the RIR contains most information and the magnitude of the late reverberation tail is insignificant. In Speech task, we observe that using RIR of entire duration and cropped RIR to have size of 0.25 seconds give similar performance. (Table 4 from FAST-RIR)

![Capture](https://user-images.githubusercontent.com/73730558/184192511-78f07dbf-a72a-4a57-93c5-38328883df38.PNG)

You also can hear plausible sound in this demo https://anton-jeran.github.io/M2IR/

**Comment by yyf17** [comment]
@anton-jeran Thanks!
